version: '3.8'
services:
  web:
    build:
      context: ./shoppinglist-be
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./shoppinglist-fe
    ports:
      - "3000:3000"
    volumes:
      - ./shoppinglist-fe:/app
    environment:
      - NODE_ENV=development